// Generated by tools/gen_car_table.py from ovl_bin/gt2_03.bin. Do not edit by hand.
//
// The five car arrays arcade mode picks from, in the order the overlay stores
// them. The game keeps no label for them: the ids and names here are ours,
// assigned by position, and the order is what the sixteen event codes
// A0S A0A A0B A0C ... A3C imply - S, A, B, C - with the rally array last.

namespace GT2Port.Multiplayer;

public sealed record CarGroup(string Id, string Name, IReadOnlyList<string> Cars);

public static class CarTable
{
    public static IReadOnlyList<CarGroup> Arcade { get; } =
    [
        new CarGroup("special", "Special", ["ldvan", "dvpgn", "bjkrn", "bistn", "frcsn", "buc9n", "usccr", "vst6n", "uv12n", "fv4gn"]),
        new CarGroup("a", "Class A", ["ccrcn", "ufc9n", "io19n", "a28sn", "m2g6n", "n24vn", "s2lgn", "k2zzn"]),
        new CarGroup("b", "Class B", ["ia54n", "gattn", "gb28n", "iictn", "h2s2n", "ilden", "gm32n", "ulpsn", "t291n"]),
        new CarGroup("c", "Class C", ["fcx8n", "q2mcn", "umcon", "bmmgn", "gotin", "fp26n", "brmcn", "x2a8n", "gv4gn"]),
        new CarGroup("rally", "Rally", ["t2cxr", "m2a5r", "s2irr", "effwr", "fp2xr", "t2rrr", "nplrr", "a2brr", "sirbr", "fcsrr", "ildrr", "goiir", "frmrr", "t28rr", "tcerr", "mlror", "mlrnr", "m2w6r", "q2xrr", "efesr", "ilstr", "fp3rr", "brm1r", "gv4rr"]),
    ];
}
