// Generated by tools/gen_course_table.py from ovl_bin/gt2_03.bin. Do not edit by hand.
//
// These are the game's own two-player course tables: 21 tarmac and
// 6 dirt, with the asset code and display name it pairs them with.

namespace GT2Port.Multiplayer;

public enum CourseSurface { Tarmac, Dirt }

public sealed record Course(string Code, string Name, CourseSurface Surface);

public static class CourseTable
{
    public static IReadOnlyList<Course> All { get; } =
    [
        new Course("tahiti_t_2p", "Tahiti Road", CourseSurface.Tarmac),
        new Course("parma_2p", "Midfield Raceway", CourseSurface.Tarmac),
        new Course("2p_testline", "High Speed Ring", CourseSurface.Tarmac),
        new Course("speed2p", "Super Speedway", CourseSurface.Tarmac),
        new Course("2p_seatt_s", "Seattle Short Course", CourseSurface.Tarmac),
        new Course("2p_roma_short", "Rome Short Course", CourseSurface.Tarmac),
        new Course("2p_sprint2", "Red Rock Valley Speedway", CourseSurface.Tarmac),
        new Course("2p_seattle", "Seattle Circuit", CourseSurface.Tarmac),
        new Course("2p_roma", "Rome Circuit", CourseSurface.Tarmac),
        new Course("Gtest", "Grindelwald", CourseSurface.Tarmac),
        new Course("laguna2p", "Laguna Seca Raceway", CourseSurface.Tarmac),
        new Course("new_parmaS_2p", "Apricot Hill Speedway", CourseSurface.Tarmac),
        new Course("2p_mountain", "Trial Mountain Circuit", CourseSurface.Tarmac),
        new Course("2p_shortway", "Clubman Stage Route 5", CourseSurface.Tarmac),
        new Course("2p_short", "Grand Valley East Section", CourseSurface.Tarmac),
        new Course("2p_circuit", "Grand Valley Speedway", CourseSurface.Tarmac),
        new Course("2p_highway", "Special Stage Route 5", CourseSurface.Tarmac),
        new Course("2p_autumn", "Autumn Ring", CourseSurface.Tarmac),
        new Course("2p_test_in2", "Deep Forest Raceway", CourseSurface.Tarmac),
        new Course("2p_roma_night", "Rome-Night", CourseSurface.Tarmac),
        new Course("2p_mini", "Autumn Ring Mini", CourseSurface.Tarmac),
        new Course("tahiti_d_new_2p", "Tahiti Dirt Route 3", CourseSurface.Dirt),
        new Course("nn_dirt_2_2p", "Smokey Mountain South", CourseSurface.Dirt),
        new Course("nn_dirt_3_2p", "Green Forest Roadway", CourseSurface.Dirt),
        new Course("no_name_dirt_2p", "Smokey Mountain North", CourseSurface.Dirt),
        new Course("pikes_2p", "Pikes Peak Hill Climb", CourseSurface.Dirt),
        new Course("pikes_2p_rev", "Pikes Peak Downhill", CourseSurface.Dirt),
    ];

    static readonly Dictionary<string, Course> ByCode =
        All.ToDictionary(c => c.Code, StringComparer.Ordinal);

    public static bool TryFind(string code, out Course course) =>
        ByCode.TryGetValue(code, out course!);

    /// <summary>
    /// The name to show for a course code. An unknown code returns itself
    /// rather than an empty string: a room announced from a disc revision this
    /// build does not know should read as something odd, not as nothing.
    /// </summary>
    public static string DisplayName(string code) =>
        ByCode.TryGetValue(code, out var course) ? course.Name : code;
}
