// Generated by tools/extract_overlays.py. Do not edit by hand.
//
// The disc the recompiled code was built from, as the six (offset, length)
// pairs that open GT2.OVL. The runtime takes its disc from settings.json and
// the code comes from config/gt2.json; when those disagree the game boots the
// wrong overlays and fails in ways that look like a missing subsystem rather
// than a wrong path. This is what makes the disagreement say so.

namespace GT2Port;

public static class DiscIdentity
{
    public const string Built = @"Gran Turismo 2 Combined Disc (USA).bin";

    public static readonly (uint Offset, uint Length)[] Overlays =
    [
        (48u, 144637u),  // gt2_01,
        (144685u, 45030u),  // gt2_02,
        (189715u, 53467u),  // gt2_03,
        (243182u, 5195u),  // gt2_04,
        (248377u, 38518u),  // gt2_05,
        (286895u, 3602u),  // gt2_06
    ];
}
