#!/usr/bin/env python3
"""Emit arcade mode's car class roster from the tables inside gt2_03.

Arcade mode picks a car class before a car; the classes and the cars in each
are two more tables the game carries but never labels. Taking the roster from
there rather than typing it out is what stops it drifting.

Run by hand after changing the overlay images, and commit the result:

    python tools/gen_car_table.py
"""
import struct
import sys

OVERLAY = 'ovl_bin/gt2_03.bin'
OUTPUT = 'patches/multiplayer/CarTable.cs'
BASE = 0x80010000
ANCHOR = b'ldvan\x00'

GROUPS = [
    ('special', 'Special'),
    ('a', 'Class A'),
    ('b', 'Class B'),
    ('c', 'Class C'),
    ('rally', 'Rally'),
]
EXPECTED_SIZES = [10, 8, 9, 9, 24]


def string_at(data, offset):
    end = data.index(b'\x00', offset)
    return data[offset:end].decode('ascii')


def code_block(data):
    """The span of the car-code strings, found rather than assumed."""
    anchor = data.find(ANCHOR)
    if anchor < 0:
        raise SystemExit(f'{OVERLAY}: the car codes are not in this image')

    def printable(i):
        return 32 <= data[i] < 127 or data[i] == 0

    start = anchor
    while start > 0 and printable(start - 1):
        start -= 1
    end = anchor
    while end < len(data) and printable(end):
        end += 1
    return start, end


def runs_of_pointers(data, lo, hi):
    """Every 4-byte-aligned pointer into [lo, hi), grouped into runs of
    pointers 4 bytes apart - i.e. the arrays of pointers-to-car-codes, the
    same shape as the arrays gen_course_table.py finds in gt2_03's
    two-player tables."""
    def in_range(pointer):
        return lo <= pointer - BASE < hi

    hits = []
    for at in range(0, len(data) - 4, 4):
        pointer = struct.unpack_from('<I', data, at)[0]
        if in_range(pointer):
            hits.append(at)

    runs = []
    for at in hits:
        if runs and at - runs[-1][-1] == 4:
            runs[-1].append(at)
        else:
            runs.append([at])
    return runs


def read(data, run):
    return [string_at(data, struct.unpack_from('<I', data, at)[0] - BASE) for at in run]


def main():
    data = open(OVERLAY, 'rb').read()
    lo, hi = code_block(data)
    all_runs = runs_of_pointers(data, lo, hi)

    sizes = [len(r) for r in all_runs if len(r) > 1]
    if sizes != EXPECTED_SIZES:
        raise SystemExit(
            f'{OVERLAY}: expected five runs of {EXPECTED_SIZES}, found run sizes '
            # Report what was actually found, not the filtered view above - a
            # run that got split into a lone pointer and the rest would
            # otherwise be reported as if the lone pointer were never there
            # at all.
            f'{[len(r) for r in all_runs]}. '
            'The overlay changed shape - read it before touching this script.')

    runs = [r for r in all_runs if len(r) > 1]

    groups = [(gid, name, read(data, run)) for (gid, name), run in zip(GROUPS, runs)]

    def cs_string(s):
        """Escape a string for a C# string literal, so a car code carrying a
        quote or backslash produces a file that still compiles."""
        return s.replace('\\', '\\\\').replace('"', '\\"')

    def cs_list(codes):
        return '[' + ', '.join(f'"{cs_string(c)}"' for c in codes) + ']'

    rows = '\n'.join(
        f'        new CarGroup("{cs_string(gid)}", "{cs_string(name)}", {cs_list(codes)}),'
        for gid, name, codes in groups)

    with open(OUTPUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(f'''// Generated by tools/gen_car_table.py from {OVERLAY}. Do not edit by hand.
//
// The five car arrays arcade mode picks from, in the order the overlay stores
// them. The game keeps no label for them: the ids and names here are ours,
// assigned by position, and the order is what the sixteen event codes
// A0S A0A A0B A0C ... A3C imply - S, A, B, C - with the rally array last.

namespace GT2Port.Multiplayer;

public sealed record CarGroup(string Id, string Name, IReadOnlyList<string> Cars);

public static class CarTable
{{
    public static IReadOnlyList<CarGroup> Arcade {{ get; }} =
    [
{rows}
    ];
}}
''')
    total = sum(len(codes) for _, _, codes in groups)
    print(f'{len(groups)} groups, {total} cars -> {OUTPUT}')


if __name__ == '__main__':
    main()
