#!/usr/bin/env python3
"""Emit the two-player course roster from the tables inside gt2_03.

The game carries, as arrays of 32-byte records, both the asset code and the
display name of every course its two-player mode offers. Taking the roster from
there rather than typing it out is what stops it drifting - and it settles
pairings nobody would guess: speed2p is Super Speedway, and Grindelwald's
two-player asset is called Gtest.

Run by hand after changing the overlay images, and commit the result:

    python tools/gen_course_table.py
"""
import struct
import sys

OVERLAY = 'ovl_bin/gt2_03.bin'
OUTPUT = 'patches/multiplayer/CourseTable.cs'
BASE = 0x80010000
RECORD = 32
CODE_PTR = 0x10
NAME_PTR = 0x14
ANCHOR = b'2p_seattle\x00'


def string_at(data, offset):
    end = data.index(b'\x00', offset)
    return data[offset:end].decode('ascii')


def code_block(data):
    """The span of the two-player asset-code strings, found rather than assumed."""
    anchor = data.find(ANCHOR)
    if anchor < 0:
        raise SystemExit(f'{OVERLAY}: the two-player course codes are not in this image')

    def printable(i):
        return 32 <= data[i] < 127 or data[i] == 0

    start = anchor
    while start > 0 and printable(start - 1):
        start -= 1
    end = anchor
    while end < len(data) and printable(end):
        end += 1
    return start, end


def records(data, lo, hi):
    """Every 32-byte record whose code pointer *and* name pointer land in [lo, hi).

    The code-string block found by code_block() is bounded by "stays
    printable-and-NUL", and in this image that span runs on, with no gap at
    all, straight into the display-name strings the same records point to
    with +0x14 - the one-player code strings sit hard up against it on the
    other side the same way. A scan that only checks the +0x10 slot for a
    pointer landing in that span can't tell a real record's own code pointer
    from its neighbour's name pointer landing in the same span 4 bytes later,
    which fragments every real run; and it can't tell a two-player record
    from a one-player one, since both code strings are in span. Requiring
    both the +0x10 and +0x14 pointers to land in [lo, hi) fixes the first
    problem outright, and leaves the second as same-sized ambiguity for the
    caller to resolve against the two record counts the game actually uses.
    """
    def in_range(pointer):
        return lo <= pointer - BASE < hi

    hits = []
    for at in range(0, len(data) - RECORD, 4):
        code_ptr = struct.unpack_from('<I', data, at + CODE_PTR)[0]
        name_ptr = struct.unpack_from('<I', data, at + NAME_PTR)[0]
        if in_range(code_ptr) and in_range(name_ptr):
            hits.append(at)

    runs = []
    for at in hits:
        if runs and at - runs[-1][-1] == RECORD:
            runs[-1].append(at)
        else:
            runs.append([at])
    return runs


def read(data, run):
    out = []
    for at in run:
        code = string_at(data, struct.unpack_from('<I', data, at + CODE_PTR)[0] - BASE)
        name = string_at(data, struct.unpack_from('<I', data, at + NAME_PTR)[0] - BASE)
        out.append((code, name))
    return out


def main():
    data = open(OVERLAY, 'rb').read()
    lo, hi = code_block(data)
    runs = [r for r in records(data, lo, hi) if len(r) > 1]

    # code_block()'s span holds the one-player code strings too (they abut
    # the two-player ones with no gap to detect), so the one-player tables
    # - forward and reversed - turn up here as further same-shaped runs.
    # What singles out the two-player tarmac and dirt tables is that no
    # other run shares their exact record count, so matching on 21 and 6
    # still identifies them uniquely without ambiguity.
    sizes = sorted(len(r) for r in runs)
    tarmac_runs = [r for r in runs if len(r) == 21]
    dirt_runs = [r for r in runs if len(r) == 6]
    if len(tarmac_runs) != 1 or len(dirt_runs) != 1:
        raise SystemExit(
            f'{OVERLAY}: expected exactly one 21-record run and one 6-record run, '
            f'found run sizes {sizes}. '
            'The overlay changed shape - read it before touching this script.')

    tarmac_run, dirt_run = tarmac_runs[0], dirt_runs[0]
    courses = ([(c, n, 'Tarmac') for c, n in read(data, tarmac_run)]
               + [(c, n, 'Dirt') for c, n in read(data, dirt_run)])

    def cs_string(s):
        """Escape a string for a C# string literal, so a course name or code
        carrying a quote or backslash produces a file that still compiles."""
        return s.replace('\\', '\\\\').replace('"', '\\"')

    rows = '\n'.join(
        f'        new Course("{cs_string(code)}", "{cs_string(name)}", CourseSurface.{surface}),'
        for code, name, surface in courses)

    with open(OUTPUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(f'''// Generated by tools/gen_course_table.py from {OVERLAY}. Do not edit by hand.
//
// These are the game's own two-player course tables: {len(tarmac_run)} tarmac and
// {len(dirt_run)} dirt, with the asset code and display name it pairs them with.

namespace GT2Port.Multiplayer;

public enum CourseSurface {{ Tarmac, Dirt }}

public sealed record Course(string Code, string Name, CourseSurface Surface);

public static class CourseTable
{{
    public static IReadOnlyList<Course> All {{ get; }} =
    [
{rows}
    ];

    static readonly Dictionary<string, Course> ByCode =
        All.ToDictionary(c => c.Code, StringComparer.Ordinal);

    public static bool TryFind(string code, out Course course) =>
        ByCode.TryGetValue(code, out course!);

    /// <summary>
    /// The name to show for a course code. An unknown code returns itself
    /// rather than an empty string: a room announced from a disc revision this
    /// build does not know should read as something odd, not as nothing.
    /// </summary>
    public static string DisplayName(string code) =>
        ByCode.TryGetValue(code, out var course) ? course.Name : code;
}}
''')
    print(f'{len(courses)} courses -> {OUTPUT}')


if __name__ == '__main__':
    main()
