#!/usr/bin/env python3
"""Generate the entry-point -> overlay table used to select an overlay.

GT2 inflates overlays into RAM itself, so nothing about the transfer says which
one arrived; the only signal is the address the loader is asked to enter. Every
overlay loads at the same base, so an address only identifies an overlay when
exactly one overlay's symbol file claims it. Ambiguous addresses are dropped
rather than guessed - picking the wrong overlay would dispatch real calls into
unrelated code, which is far worse than failing loudly.
"""
import argparse
import pathlib
import re

SYM = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*0x([0-9A-Fa-f]{8})")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("config_dir", help="gt2-reversing config dir holding ovrN_symbol_addrs.txt")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--base", default="0x80010000")
    ap.add_argument("--limit", default="0x8005D600", help="overlays live below the main text")
    args = ap.parse_args()

    base, limit = int(args.base, 16), int(args.limit, 16)
    claims: dict[int, set[int]] = {}
    names: dict[int, str] = {}
    for i in range(1, 7):
        path = pathlib.Path(args.config_dir) / f"ovr{i}_symbol_addrs.txt"
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            m = SYM.match(line)
            if not m:
                continue
            addr = int(m.group(2), 16)
            if not base <= addr < limit:
                continue
            claims.setdefault(addr, set()).add(i)
            names.setdefault(addr, m.group(1))

    unique = {a: next(iter(o)) for a, o in claims.items() if len(o) == 1}
    ambiguous = len(claims) - len(unique)

    lines = [
        "// Generated by tools/gen_overlay_map.py - do not edit by hand.",
        "// Maps an overlay entry address to the overlay that owns it.",
        "",
        "namespace GT2Port;",
        "",
        "public static partial class OverlayHook",
        "{",
        "    static readonly Dictionary<uint, string> ByEntryPoint = new()",
        "    {",
    ]
    for addr in sorted(unique):
        lines.append(f'        [0x{addr:08X}u] = "gt2_0{unique[addr]}", // {names[addr]}')
    lines += ["    };", "}", ""]

    pathlib.Path(args.out).write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{args.out}: {len(unique)} unambiguous entry points "
          f"({ambiguous} addresses claimed by more than one overlay, dropped)")


if __name__ == "__main__":
    main()
